ALTER TYPE "SideMarketType" ADD VALUE 'CONTRIBUTOR';
ALTER TYPE "SideMarketPickPhase" ADD VALUE 'FINAL';

ALTER TYPE "MiniBetType" ADD VALUE 'PLAYER_GOAL_OR_ASSIST';
ALTER TYPE "MiniBetType" ADD VALUE 'POSSESSION';
ALTER TYPE "MiniBetType" ADD VALUE 'YELLOW_CARDS_3';
ALTER TYPE "MiniBetType" ADD VALUE 'OFFSIDES_3';
ALTER TYPE "MiniBetType" ADD VALUE 'EXTRA_TIME';
ALTER TYPE "MiniBetType" ADD VALUE 'EXACT_SCORE';

ALTER TYPE "MiniBetChoice" ADD VALUE 'SCORE_0_0';
ALTER TYPE "MiniBetChoice" ADD VALUE 'SCORE_1_0';
ALTER TYPE "MiniBetChoice" ADD VALUE 'SCORE_1_1';
ALTER TYPE "MiniBetChoice" ADD VALUE 'SCORE_2_0';
ALTER TYPE "MiniBetChoice" ADD VALUE 'SCORE_2_1';
ALTER TYPE "MiniBetChoice" ADD VALUE 'SCORE_2_2';
ALTER TYPE "MiniBetChoice" ADD VALUE 'SCORE_3_0';
ALTER TYPE "MiniBetChoice" ADD VALUE 'SCORE_3_1';
ALTER TYPE "MiniBetChoice" ADD VALUE 'SCORE_3_2';
