ALTER TYPE "RoundType" ADD VALUE IF NOT EXISTS 'THIRD_PLACE' BEFORE 'FINAL';

ALTER TABLE "Match"
ADD COLUMN "teamACode" TEXT,
ADD COLUMN "teamBCode" TEXT,
ADD COLUMN "teamACrest" TEXT,
ADD COLUMN "teamBCrest" TEXT;
